apiVersion: v2
name: argocd-root-chart
description: App of Apps for Kubernetes Cluster
type: application
version: 0.1.1
appVersion: 1.0.0
keywords:
  - argocd
  - gitops
sources:
  - https://github.com/atrakic/argocd-root-chart
