# Default values for argocd-root-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Globals
destinationServer: 'https://kubernetes.default.svc'
argoNamespace: 'argocd'
argoProject: 'default'

## Operators

certManager:
  enable: true
  serviceAccountName:

ingressNginx:
  enable: true

externalSecrets:
  enable: true

prometheus:
  enable: true
  namespace: observability

promtheusNodeExporter:
  enable: true
  namespace: observability

## Disabled ##

clusterAutoscaler:
  enable: false
  serviceAccountName:
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi

externalDns:
  enable: false
  zoneIdFilter:
  #provider: "aws"

argoRollouts:
  enable: false

argoWorkflows:
  enable: false

kubeStateMetrics:
  enable: false
  namespace: observability

kubePrometheusStack:
  enable: false
  namespace: observability

metricsServer:
  enable: false
  namespace: observability
  replicas: 3
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1


kubernetesDashboard:
  enable: false
  namespace: observability

promtail:
  enable: false
  namespace: observability

opentelemetryCollector:
  enable: false
  namespace: observability

## __end__
