# Default values for argocd-root-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

repoUrl: 'https://github.com/atrakic/argocd-root-chart.git'
targetRevision: HEAD
destinationServer: ''
argoNamespace: 'argocd'
argoProject: 'default'

certManager:
  enable: true
  serviceAccountName:

clusterAutoscaler:
  enable: true
  serviceAccountName:
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi

externalDns:
  enable: true
  zoneIdFilter:
  #provider: "aws"

externalSecrets:
  enable: true

ingressNginx:
  enable: true
  controller:
    service:
      #externalTrafficPolicy: "Local"
      #annotations:

grafana:
  enable: true
  serviceAccount:
    create: true

metricsServer:
  enable: true
  replicas: 3
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

prometheus:
  enable: true
  serviceAccountName:
  roleArn:
  ampWorkspaceUrl:

sparkOperator:
  enable: true
  createNamespace: true

argoRollouts:
  enable: true
  createNamespace: true

argoWorkflows:
  enable: true

kubeStateMetrics:
  enable: true
  createNamespace: true
  serviceAccountName:

promtheusNodeExporter:
  enable: true
  serviceAccountName:

kubernetesDashboard:
  enable: true
  serviceAccountName:

promtail:
  enable: true

kubePrometheusStack:
  enable: true

opentelemetryCollector:
  enable: true
  serviceAccountName:
