# Default values for argocd-root-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

repoUrl: 'https://github.com/atrakic/argocd-root-chart.git'
targetRevision: HEAD

region: ''
account: ''
clusterName: ''
destinationServer: ''
argoNamespace: ''
argoProject: ''

certManager:
  enable: true
  createNamespace: true
  serviceAccountName:

clusterAutoscaler:
  enable: true
  serviceAccountName:

externalDns:
  enable: true
  createNamespace: true
  serviceAccountName:
  zoneIdFilter:

externalSecrets:
  enable: true

ingressNginx:
  enable: true
  createNamespace: true

grafana:
  enable: true
  serviceAccount:
    create: true

vault:
  enable: true

metricsServer:
  enable: true

prometheus:
  enable: true
  createNamespace: true
  serviceAccountName:
  roleArn:
  ampWorkspaceUrl:

sparkOperator:
  enable: true
  createNamespace: true

argoRollouts:
  enable: true
  createNamespace: true

argoWorkflows:
  enable: true

kubeStateMetrics:
  enable: true
  createNamespace: true
  serviceAccountName:

promtheusNodeExporter:
  enable: true
  serviceAccountName:

kubernetesDashboard:
  enable: true
  serviceAccountName:

promtail:
  enable: true

kubecost:
  enable: true

reloader:
  enable: true

kubePrometheusStack:
  enable: true

kyverno:
  enable: true

policies:
  enable: true

reporter:
  enable: true

velero:
  enable: true

opentelemetryCollector:
  enable: true
  serviceAccountName:
