# Default values for argocd-root-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Globals
destinationServer: 'https://kubernetes.default.svc'
argoNamespace: 'argocd'
argoProject: 'default'


## Operators

certManager:
  enable: true
  serviceAccountName:

ingressNginx:
  enable: true
  controller:
    service:
      #externalTrafficPolicy: "Local"
      #annotations:

clusterAutoscaler:
  enable: false
  serviceAccountName:
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi

externalDns:
  enable: false
  zoneIdFilter:
  #provider: "aws"

externalSecrets:
  enable: false

grafana:
  enable: false
  serviceAccount:
    create: false

metricsServer:
  enable: false
  replicas: 3
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

prometheus:
  enable: false

sparkOperator:
  enable: false
  createNamespace: true

argoRollouts:
  enable: false
  createNamespace: true

argoWorkflows:
  enable: false

kubeStateMetrics:
  enable: false
  createNamespace: true

promtheusNodeExporter:
  enable: false

kubernetesDashboard:
  enable: false

promtail:
  enable: false

kubePrometheusStack:
  enable: false

opentelemetryCollector:
  enable: false
