{{- if and (.Values.certManager) (.Values.certManager.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.10.1
    helm:
      values: |
        cert-manager:
        {{- toYaml .Values.certManager | nindent 10 }}
      parameters:
        - name: installCRDs
          value: 'true'
        - name: prometheus.servicemonitor.enabled
          value: 'false'
        - name: prometheus.servicemonitor.honorLabels
          value: 'true'
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end -}}
