{{- if and (.Values.clusterAutoscaler) (.Values.clusterAutoscaler.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.19.2
    chart: cluster-autoscaler
    helm:
      values: |
        cluster-autoscaler:
          rbac:
            serviceAccount:
              create: false
        {{- toYaml .Values.clusterAutoscaler | nindent 10 }}
      parameters:
      - name: cluster-autoscaler.awsRegion
        value: {{ .Values.region }}
      - name: cluster-autoscaler.rbac.serviceAccount.name
        value: {{ .Values.clusterAutoscaler.serviceAccountName }}
      - name: cluster-autoscaler.autoDiscovery.clusterName
        value: {{ .Values.clusterName }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
