{{- if and (.Values.externalDns) (.Values.externalDns.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.13.1
    chart: external-dns
    helm:
      values: |
        external-dns:
            serviceAccount:
              create: false
        {{- toYaml .Values.externalDns | nindent 10 }}
      parameters:
      - name: external-dns.aws.region
        value: {{ .Values.region }}
      - name: external-dns.serviceAccount.name
        value: {{ .Values.externalDns.serviceAccountName }}
      - name: external-dns.zoneIdFilters[0]
        value: {{ .Values.externalDns.zoneIdFilter }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.externalDns.namespace | default "external-dns" }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end -}}
