{{- if and (.Values.externalSecrets) (.Values.externalSecrets.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: 'https://charts.external-secrets.io/'
    targetRevision: {{ .Values.externalSecrets.targetRevision | default "0.7.2" }}
    chart: external-secrets
    helm:
      values: |
        external-secrets:
        {{- toYaml .Values.externalSecrets | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.externalSecrets.namespace | default "external-secrets" }}
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
{{- end -}}
