apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.infra.name }}
  namespace: {{ .Values.spec.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: {{ .Values.infra.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    chart: {{ .Values.infra.chart }}
    repoURL: {{ .Values.infra.repoURL }}
    targetRevision: {{ .Values.infra.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
