{{- if and (.Values.ingressNginx) (.Values.ingressNginx.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.1.4
    chart: ingress-nginx
    helm:
      values: |
        ingress-nginx:
          controller:
            updateStrategy:
              type: "RollingUpdate"
              rollingUpdate:
                maxUnavailable: 1
        metrics:
          port: 10254
          enabled: true
          service:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "10254"
        #admissionWebhooks:
        #  enabled: false
        {{- toYaml .Values.ingressNginx | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- end -}}
