{{- if and (.Values.prometheusNodeExporter) (.Values.prometheusNodeExporter.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-node-exporter
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 4.13.0
    chart: prometheus-node-exporter
    helm:
      values: |
        prometheus-node-exporter:
          serviceAccount:
            create: false
        {{- toYaml .Values.promtheusNodeExporter | nindent 10 }}
      parameters:
      - name: prometheus-node-exporter.serviceAccount.name
        value: {{ .Values.promtheusNodeExporter.serviceAccountName }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.promtheusNodeExporter.namespace | default "prom-node-exporter" }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
